"""Interface (contrato) dos backends de repositório.

Documenta as operações que `FilesRepo` e `SqliteRepo` devem implementar.
As assinaturas espelham as fachadas `storage.py` / `state.py`.
"""
from __future__ import annotations
from typing import Dict, List, Optional, Protocol
from ..core.models import Prova, Pilot


class Repo(Protocol):
    # ---- provas ----
    def list_provas(self) -> List[Prova]: ...
    def provas_by_slug(self) -> Dict[str, Prova]: ...
    def get_prova(self, slug: str) -> Optional[Prova]: ...
    def save_prova(self, prova: Prova) -> None: ...

    # ---- competições ----
    def list_competicoes(self) -> List[dict]: ...
    def get_competicao(self, slug: str) -> Optional[dict]: ...

    # ---- pilotos / tracks ----
    def add_pilot(self, slug: str, pilot: Pilot) -> None: ...
    def pilots(self, slug: str) -> List[Pilot]: ...
    def remove_pilot(self, slug: str, bib: str) -> None: ...
    def set_declared(self, slug: str, bib: str, tg_name: str, sec_utc) -> None: ...
    def reset(self, slug: Optional[str] = None) -> None: ...
